name: Docker Image CI Dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and Push Docker Image
        run: |
          DOCKER_USERNAME=shivaaws69
          DOCKER_PASSWORD='dckr_pat_-Q2PitIFrBPrHBqRAfcM9qiShts'

          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

          # docker build -t $DOCKER_USERNAME/demo_nodejs_webpage:latest .
          # docker push $DOCKER_USERNAME/demo_nodejs_webpage:latest
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)

          IMAGE_NAME=$DOCKER_USERNAME/demo_nodejs_webpage

          echo "Building image with tag: $SHORT_SHA"

          # Build image
          docker build -t $IMAGE_NAME:$SHORT_SHA .

          # Push image
          docker push $IMAGE_NAME:$SHORT_SHA
