name: Docker Image CI Dev

on:
  push:
    branches: [ "dev" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Step 1: Set Semantic Version
      - name: Set Version
        run: |
          BASE_VERSION=1.0.0

          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
            VERSION=v${BASE_VERSION}-dev-${SHORT_SHA}
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Image version: $VERSION"

      # Step 2: Docker Login
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      # Step 3: Build and Push
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/demo_nodejs_webpage

          echo "Building image: $IMAGE_NAME:$VERSION"

          docker build -t $IMAGE_NAME:$VERSION .
          docker push $IMAGE_NAME:$VERSION
